### ISSUE TITLE
Use custom post type label for notifications

### ISSUE THREAD

**Issue by tripflex** [Desertsnowman/UIX#10]
![](https://smyl.es/img/Screenshot_2016-09-14_12-45-53_PM.png)

You will notice in the image above, the notifications (like "post updated") ... say **Post** instead of using the singular label from the post type.  I know the "Edit Post" and "Add New Post" can all be set using the keys for the `register_post_type`, but i don't think the notifications can be set through the config

Would be good to have those (and any others you can think of) to say the post label instead of post

**Comment by DavidCramer** [comment]
OK,  I'll add those

**Comment by DavidCramer** [comment]
Can use all args used in standard register post type.
