### ISSUE TITLE
PHP files created using package.json from uix

### ISSUE THREAD

**Issue by tripflex** [Desertsnowman/UIX#7]
When using grunt, the files that are generated seem to be using the data from the uix `package.json` file instead of the one from the uix-wp directory

**Comment by tripflex** [comment]
The `NAMESPACE-bootstrap.php` file that is

**Comment by tripflex** [comment]
Also looks like the headers in the `NAMESPACE-bootstrap` file need to be removed to prevent duplicate plugins from showing in plugins.php age

**Comment by DavidCramer** [comment]
sorry I haven't tested the installer properly since the updates. I'll update it

**Comment by DavidCramer** [comment]
this is sorted now.

**Comment by tripflex** [comment]
You sure?

This is the plugin you released showing in plugins page:
![](https://smyl.es/img/Screenshot_2016-10-19_03-09-55_PM.png)
