### ISSUE TITLE
Fatal error, incorrect extends class

### ISSUE THREAD

**Issue by tripflex** [Desertsnowman/UIX#8]
https://github.com/Desertsnowman/uix/blob/master/classes/uix/data/data.php#L14

`extends \uix\ui\uix` should probably just be `extends \uix\ui`

https://github.com/Desertsnowman/uix-wp/issues/1

**Comment by tripflex** [comment]
Unless it's meant to extend this:
https://github.com/Desertsnowman/uix/blob/master/classes/uix/ui/uix.php

Which in that case, this fatal error is thrown then:
Fatal error: Class 'myplugin\ui\myplugin' not found in /app/public/wp-content/plugins/uix-wp/classes/myplugin/data/data.php on line 14

**Comment by DavidCramer** [comment]
Sorry, corrected it. I hadn't made all the changes to the installer. should work fine now.

**Comment by tripflex** [comment]
Yup works great now, thanks!
