### ISSUE TITLE
Example code for post_type directory issues

### ISSUE THREAD

**Issue by tripflex** [Desertsnowman/UIX#9]
The `employee_bio` array key is missing the surrounding quotes, also, the metabox should show the fields added in the config correct?

This is what the demo code shows (after adding quotes around `employee_bio`):
![](https://smyl.es/img/Screenshot_2016-09-14_12-36-54_PM.png)

**Comment by DavidCramer** [comment]
maybe I should add some working examples

**Comment by tripflex** [comment]
Yeah I think to increase visibility and help out those who are trying to learn, it would be best to have a test plugin that demos all the available features ... so basically a full blown demo plugin, with examples of each feature included.  

That way new users could literally copy and paste the code and then edit as they need, and as they start using it, they will learn how the framework works and be able to start customizing even more.

I know that when Piklist finally added full blown examples, their popularity shot up tremendously 👍   Let me know if i can help in any way

**Comment by DavidCramer** [comment]
Working example in readme.
